language: ruby
before_script:
  - cp config/database.travis.yml config/database.yml
script: 
  - RAILS_ENV=test bundle exec db:create db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
rvm:
  - "2.1.0"
